In [ ]:
# clean

In [2]:
# Data Science Dependencies
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd

# Linear Algorithms
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier

# Decision Tree Algorithms
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, ExtraTreesClassifier, GradientBoostingClassifier
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier

# Machine Learning Processing and Evaluation Metrics
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler, LabelEncoder
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score, roc_curve

In [3]:
# Pandas display options
pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", None)
pd.set_option("display.max_rows", None)

In [5]:
# Datasets
train_df = pd.read_csv('Resources/2019loans.csv')
test_df = pd.read_csv('Resources/2020Q1loans.csv')

In [6]:
# EDA "Train_df" data
train_df.head()

,Unnamed: 0,index,loan_amnt,int_rate,installment,home_ownership,annual_inc,verification_status,loan_status,pymnt_plan,dti,delinq_2yrs,inq_last_6mths,open_acc,pub_rec,revol_bal,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_amnt,collections_12_mths_ex_med,policy_code,application_type,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_inq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,debt_settlement_flag
0,57107,57107,13375.0,0.1797,483.34,MORTGAGE,223000.0,Not Verified,low_risk,n,29.99,0.0,0.0,15.0,0.0,39728.0,38.0,w,12804.66,12804.66,953.33,953.33,570.34,382.99,0.0,0.0,0.0,483.34,0.0,1.0,Individual,0.0,0.0,465790.0,2.0,7.0,3.0,7.0,7.0,82290.0,70.0,1.0,1.0,24683.0,69.0,60200.0,1.0,12.0,2.0,9.0,31053.0,7317.0,77.1,0.0,0.0,160.0,350.0,3.0,3.0,1.0,3.0,8.0,0.0,1.0,4.0,2.0,5.0,18.0,7.0,17.0,4.0,15.0,0.0,0.0,0.0,5.0,100.0,50.0,0.0,0.0,577150.0,122018.0,32000.0,170200.0,N,N
1,141451,141451,21000.0,0.1308,478.68,MORTGAGE,123000.0,Source Verified,low_risk,n,11.26,2.0,0.0,16.0,0.0,9585.0,20.0,w,15152.97,15152.97,10037.02,10037.02,5847.03,4189.99,0.0,0.0,0.0,478.68,0.0,1.0,Individual,0.0,0.0,60769.0,0.0,2.0,0.0,1.0,17.0,18311.0,52.0,0.0,4.0,4311.0,50.0,20900.0,1.0,0.0,1.0,5.0,3798.0,6990.0,56.0,0.0,0.0,165.0,142.0,13.0,13.0,1.0,17.0,10.0,1.0,5.0,8.0,6.0,7.0,5.0,13.0,14.0,8.0,16.0,0.0,0.0,0.0,0.0,85.0,33.3,0.0,0.0,132750.0,27896.0,15900.0,35398.0,N,N
2,321143,321143,20000.0,0.1240,448.95,MORTGAGE,197000.0,Source Verified,low_risk,n,11.28,0.0,0.0,12.0,0.0,16708.0,36.0,w,15724.23,15724.23,6971.52,6971.52,4275.77,2695.75,0.0,0.0,0.0,448.95,0.0,1.0,Individual,0.0,0.0,617946.0,1.0,7.0,1.0,2.0,5.0,97335.0,108.0,0.0,0.0,11026.0,98.0,25900.0,2.0,0.0,2.0,3.0,51496.0,5892.0,73.9,0.0,0.0,254.0,239.0,30.0,5.0,3.0,173.0,5.0,1.0,3.0,3.0,3.0,5.0,26.0,4.0,7.0,3.0,12.0,0.0,0.0,0.0,1.0,85.7,33.3,0.0,0.0,628160.0,114043.0,22600.0,90340.0,N,N
3,11778,11778,3000.0,0.1240,100.22,RENT,45000.0,Not Verified,low_risk,n,18.08,0.0,0.0,12.0,1.0,8809.0,19.0,w,2930.77,2930.77,81.63,81.63,69.23,12.40,0.0,0.0,0.0,85.76,1.0,1.0,Individual,0.0,568.0,20761.0,2.0,4.0,2.0,2.0,8.0,11952.0,78.0,2.0,4.0,2409.0,49.0,26600.0,4.0,4.0,2.0,6.0,1730.0,13470.0,32.3,0.0,0.0,135.0,146.0,2.0,2.0,0.0,2.0,8.0,0.0,5.0,6.0,6.0,6.0,8.0,8.0,11.0,6.0,12.0,0.0,0.0,0.0,4.0,100.0,16.7,1.0,0.0,42006.0,20761.0,19900.0,15406.0,N,N
4,169382,169382,30000.0,0.1612,1056.49,MORTGAGE,133000.0,Source Verified,low_risk,n,27.77,0.0,2.0,13.0,0.0,65420.0,51.0,w,20778.03,20778.03,14763.99,14763.99,9221.97,5542.02,0.0,0.0,0.0,1056.49,0.0,1.0,Individual,0.0,0.0,237839.0,2.0,3.0,1.0,3.0,5.0,43636.0,74.0,1.0,1.0,19804.0,74.0,88100.0,2.0,11.0,3.0,4.0,18295.0,18517.0,76.7,0.0,0.0,174.0,369.0,1.0,1.0,2.0,34.0,0.0,0.0,6.0,9.0,6.0,19.0,17.0,9.0,32.0,9.0,13.0,0.0,0.0,0.0,2.0,100.0,66.7,0.0,0.0,283248.0,109056.0,79500.0,58778.0,N,N

In [7]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12180 entries, 0 to 12179
Data columns (total 86 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Unnamed: 0                  12180 non-null  int64
 1   index                       12180 non-null  int64
 2   loan_amnt                   12180 non-null  float64
 3   int_rate                    12180 non-null  float64
 4   installment                 12180 non-null  float64
 5   home_ownership              12180 non-null  object
 6   annual_inc                  12180 non-null  float64
 7   verification_status         12180 non-null  object
 8   loan_status                 12180 non-null  object
 9   pymnt_plan                  12180 non-null  object
 10  dti                         12180 non-null  float64
 11  delinq_2yrs                 12180 non-null  float64
 12  inq_last_6mths              12180 non-null  float64
 13  open_acc                    12180 non-null  float64
 14  pub_rec                     12180 non-null  float64
 15  revol_bal                   12180 non-null  float64
 16  total_acc                   12180 non-null  float64
 17  initial_list_status         12180 non-null  object
 18  out_prncp                   12180 non-null  float64
 19  out_prncp_inv               12180 non-null  float64
 20  total_pymnt                 12180 non-null  float64
 21  total_pymnt_inv             12180 non-null  float64
 22  total_rec_prncp             12180 non-null  float64
 23  total_rec_int               12180 non-null  float64
 24  total_rec_late_fee          12180 non-null  float64
 25  recoveries                  12180 non-null  float64
 26  collection_recovery_fee     12180 non-null  float64
 27  last_pymnt_amnt             12180 non-null  float64
 28  collections_12_mths_ex_med  12180 non-null  float64
 29  policy_code                 12180 non-null  float64
 30  application_type            12180 non-null  object
 31  acc_now_delinq              12180 non-null  float64
 32  tot_coll_amt                12180 non-null  float64
 33  tot_cur_bal                 12180 non-null  float64
 34  open_acc_6m                 12180 non-null  float64
 35  open_act_il                 12180 non-null  float64
 36  open_il_12m                 12180 non-null  float64
 37  open_il_24m                 12180 non-null  float64
 38  mths_since_rcnt_il          12180 non-null  float64
 39  total_bal_il                12180 non-null  float64
 40  il_util                     12180 non-null  float64
 41  open_rv_12m                 12180 non-null  float64
 42  open_rv_24m                 12180 non-null  float64
 43  max_bal_bc                  12180 non-null  float64
 44  all_util                    12180 non-null  float64
 45  total_rev_hi_lim            12180 non-null  float64
 46  inq_fi                      12180 non-null  float64
 47  total_cu_tl                 12180 non-null  float64
 48  inq_last_12m                12180 non-null  float64
 49  acc_open_past_24mths        12180 non-null  float64
 50  avg_cur_bal                 12180 non-null  float64
 51  bc_open_to_buy              12180 non-null  float64
 52  bc_util                     12180 non-null  float64
 53  chargeoff_within_12_mths    12180 non-null  float64
 54  delinq_amnt                 12180 non-null  float64
 55  mo_sin_old_il_acct          12180 non-null  float64
 56  mo_sin_old_rev_tl_op        12180 non-null  float64
 57  mo_sin_rcnt_rev_tl_op       12180 non-null  float64
 58  mo_sin_rcnt_tl              12180 non-null  float64
 59  mort_acc                    12180 non-null  float64
 60  mths_since_recent_bc        12180 non-null  float64
 61  mths_since_recent_inq       12180 non-null  float64
 62  num_accts_ever_120_pd       12180 non-null  float64
 63  num_actv_bc_tl              12180 non-null  float64
 64  num_actv_rev_tl             12180 non-null  float64
 65  num_bc_sats                 12180 non-null  float64
 66  num_bc_tl                   12180 non-null  float64
 67  num_il_tl                   12180 non-null  float64
 68  num_op_rev_tl               12180 non-null  float64
 69  num_rev_accts               12180 non-null  float64
 70  num_rev_tl_bal_gt_0         12180 non-null  float64
 71  num_sats                    12180 non-null  float64
 72  num_tl_120dpd_2m            12180 non-null  float64
 73  num_tl_30dpd                12180 non-null  float64
 74  num_tl_90g_dpd_24m          12180 non-null  float64
 75  num_tl_op_past_12m          12180 non-null  float64
 76  pct_tl_nvr_dlq              12180 non-null  float64
 77  percent_bc_gt_75            12180 non-null  float64
 78  pub_rec_bankruptcies        12180 non-null  float64
 79  tax_liens                   12180 non-null  float64
 80  tot_hi_cred_lim             12180 non-null  float64
 81  total_bal_ex_mort           12180 non-null  float64
 82  total_bc_limit              12180 non-null  float64
 83  total_il_high_credit_limit  12180 non-null  float64
 84  hardship_flag               12180 non-null  object
 85  debt_settlement_flag        12180 non-null  object
dtypes: float64(76), int64(2), object(8)
memory usage: 8.0+ MB

In [8]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4702 entries, 0 to 4701
Data columns (total 86 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Unnamed: 0                  4702 non-null   int64
 1   index                       4702 non-null   int64
 2   loan_amnt                   4702 non-null   float64
 3   int_rate                    4702 non-null   float64
 4   installment                 4702 non-null   float64
 5   home_ownership              4702 non-null   object
 6   annual_inc                  4702 non-null   float64
 7   verification_status         4702 non-null   object
 8   loan_status                 4702 non-null   object
 9   pymnt_plan                  4702 non-null   object
 10  dti                         4702 non-null   float64
 11  delinq_2yrs                 4702 non-null   float64
 12  inq_last_6mths              4702 non-null   float64
 13  open_acc                    4702 non-null   float64
 14  pub_rec                     4702 non-null   float64
 15  revol_bal                   4702 non-null   float64
 16  total_acc                   4702 non-null   float64
 17  initial_list_status         4702 non-null   object
 18  out_prncp                   4702 non-null   float64
 19  out_prncp_inv               4702 non-null   float64
 20  total_pymnt                 4702 non-null   float64
 21  total_pymnt_inv             4702 non-null   float64
 22  total_rec_prncp             4702 non-null   float64
 23  total_rec_int               4702 non-null   float64
 24  total_rec_late_fee          4702 non-null   float64
 25  recoveries                  4702 non-null   float64
 26  collection_recovery_fee     4702 non-null   float64
 27  last_pymnt_amnt             4702 non-null   float64
 28  collections_12_mths_ex_med  4702 non-null   float64
 29  policy_code                 4702 non-null   float64
 30  application_type            4702 non-null   object
 31  acc_now_delinq              4702 non-null   float64
 32  tot_coll_amt                4702 non-null   float64
 33  tot_cur_bal                 4702 non-null   float64
 34  open_acc_6m                 4702 non-null   float64
 35  open_act_il                 4702 non-null   float64
 36  open_il_12m                 4702 non-null   float64
 37  open_il_24m                 4702 non-null   float64
 38  mths_since_rcnt_il          4702 non-null   float64
 39  total_bal_il                4702 non-null   float64
 40  il_util                     4702 non-null   float64
 41  open_rv_12m                 4702 non-null   float64
 42  open_rv_24m                 4702 non-null   float64
 43  max_bal_bc                  4702 non-null   float64
 44  all_util                    4702 non-null   float64
 45  total_rev_hi_lim            4702 non-null   float64
 46  inq_fi                      4702 non-null   float64
 47  total_cu_tl                 4702 non-null   float64
 48  inq_last_12m                4702 non-null   float64
 49  acc_open_past_24mths        4702 non-null   float64
 50  avg_cur_bal                 4702 non-null   float64
 51  bc_open_to_buy              4702 non-null   float64
 52  bc_util                     4702 non-null   float64
 53  chargeoff_within_12_mths    4702 non-null   float64
 54  delinq_amnt                 4702 non-null   float64
 55  mo_sin_old_il_acct          4702 non-null   float64
 56  mo_sin_old_rev_tl_op        4702 non-null   float64
 57  mo_sin_rcnt_rev_tl_op       4702 non-null   float64
 58  mo_sin_rcnt_tl              4702 non-null   float64
 59  mort_acc                    4702 non-null   float64
 60  mths_since_recent_bc        4702 non-null   float64
 61  mths_since_recent_inq       4702 non-null   float64
 62  num_accts_ever_120_pd       4702 non-null   float64
 63  num_actv_bc_tl              4702 non-null   float64
 64  num_actv_rev_tl             4702 non-null   float64
 65  num_bc_sats                 4702 non-null   float64
 66  num_bc_tl                   4702 non-null   float64
 67  num_il_tl                   4702 non-null   float64
 68  num_op_rev_tl               4702 non-null   float64
 69  num_rev_accts               4702 non-null   float64
 70  num_rev_tl_bal_gt_0         4702 non-null   float64
 71  num_sats                    4702 non-null   float64
 72  num_tl_120dpd_2m            4702 non-null   float64
 73  num_tl_30dpd                4702 non-null   float64
 74  num_tl_90g_dpd_24m          4702 non-null   float64
 75  num_tl_op_past_12m          4702 non-null   float64
 76  pct_tl_nvr_dlq              4702 non-null   float64
 77  percent_bc_gt_75            4702 non-null   float64
 78  pub_rec_bankruptcies        4702 non-null   float64
 79  tax_liens                   4702 non-null   float64
 80  tot_hi_cred_lim             4702 non-null   float64
 81  total_bal_ex_mort           4702 non-null   float64
 82  total_bc_limit              4702 non-null   float64
 83  total_il_high_credit_limit  4702 non-null   float64
 84  hardship_flag               4702 non-null   object
 85  debt_settlement_flag        4702 non-null   object
dtypes: float64(76), int64(2), object(8)
memory usage: 3.1+ MB

In [9]:
# Remove columns deemed unnecessary from both data sets
train_df.drop(["Unnamed: 0", "index"], axis=1, inplace=True)
test_df.drop(["Unnamed: 0", "index"], axis=1, inplace=True)

In [12]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12180 entries, 0 to 12179
Data columns (total 84 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   loan_amnt                   12180 non-null  float64
 1   int_rate                    12180 non-null  float64
 2   installment                 12180 non-null  float64
 3   home_ownership              12180 non-null  object
 4   annual_inc                  12180 non-null  float64
 5   verification_status         12180 non-null  object
 6   loan_status                 12180 non-null  object
 7   pymnt_plan                  12180 non-null  object
 8   dti                         12180 non-null  float64
 9   delinq_2yrs                 12180 non-null  float64
 10  inq_last_6mths              12180 non-null  float64
 11  open_acc                    12180 non-null  float64
 12  pub_rec                     12180 non-null  float64
 13  revol_bal                   12180 non-null  float64
 14  total_acc                   12180 non-null  float64
 15  initial_list_status         12180 non-null  object
 16  out_prncp                   12180 non-null  float64
 17  out_prncp_inv               12180 non-null  float64
 18  total_pymnt                 12180 non-null  float64
 19  total_pymnt_inv             12180 non-null  float64
 20  total_rec_prncp             12180 non-null  float64
 21  total_rec_int               12180 non-null  float64
 22  total_rec_late_fee          12180 non-null  float64
 23  recoveries                  12180 non-null  float64
 24  collection_recovery_fee     12180 non-null  float64
 25  last_pymnt_amnt             12180 non-null  float64
 26  collections_12_mths_ex_med  12180 non-null  float64
 27  policy_code                 12180 non-null  float64
 28  application_type            12180 non-null  object
 29  acc_now_delinq              12180 non-null  float64
 30  tot_coll_amt                12180 non-null  float64
 31  tot_cur_bal                 12180 non-null  float64
 32  open_acc_6m                 12180 non-null  float64
 33  open_act_il                 12180 non-null  float64
 34  open_il_12m                 12180 non-null  float64
 35  open_il_24m                 12180 non-null  float64
 36  mths_since_rcnt_il          12180 non-null  float64
 37  total_bal_il                12180 non-null  float64
 38  il_util                     12180 non-null  float64
 39  open_rv_12m                 12180 non-null  float64
 40  open_rv_24m                 12180 non-null  float64
 41  max_bal_bc                  12180 non-null  float64
 42  all_util                    12180 non-null  float64
 43  total_rev_hi_lim            12180 non-null  float64
 44  inq_fi                      12180 non-null  float64
 45  total_cu_tl                 12180 non-null  float64
 46  inq_last_12m                12180 non-null  float64
 47  acc_open_past_24mths        12180 non-null  float64
 48  avg_cur_bal                 12180 non-null  float64
 49  bc_open_to_buy              12180 non-null  float64
 50  bc_util                     12180 non-null  float64
 51  chargeoff_within_12_mths    12180 non-null  float64
 52  delinq_amnt                 12180 non-null  float64
 53  mo_sin_old_il_acct          12180 non-null  float64
 54  mo_sin_old_rev_tl_op        12180 non-null  float64
 55  mo_sin_rcnt_rev_tl_op       12180 non-null  float64
 56  mo_sin_rcnt_tl              12180 non-null  float64
 57  mort_acc                    12180 non-null  float64
 58  mths_since_recent_bc        12180 non-null  float64
 59  mths_since_recent_inq       12180 non-null  float64
 60  num_accts_ever_120_pd       12180 non-null  float64
 61  num_actv_bc_tl              12180 non-null  float64
 62  num_actv_rev_tl             12180 non-null  float64
 63  num_bc_sats                 12180 non-null  float64
 64  num_bc_tl                   12180 non-null  float64
 65  num_il_tl                   12180 non-null  float64
 66  num_op_rev_tl               12180 non-null  float64
 67  num_rev_accts               12180 non-null  float64
 68  num_rev_tl_bal_gt_0         12180 non-null  float64
 69  num_sats                    12180 non-null  float64
 70  num_tl_120dpd_2m            12180 non-null  float64
 71  num_tl_30dpd                12180 non-null  float64
 72  num_tl_90g_dpd_24m          12180 non-null  float64
 73  num_tl_op_past_12m          12180 non-null  float64
 74  pct_tl_nvr_dlq              12180 non-null  float64
 75  percent_bc_gt_75            12180 non-null  float64
 76  pub_rec_bankruptcies        12180 non-null  float64
 77  tax_liens                   12180 non-null  float64
 78  tot_hi_cred_lim             12180 non-null  float64
 79  total_bal_ex_mort           12180 non-null  float64
 80  total_bc_limit              12180 non-null  float64
 81  total_il_high_credit_limit  12180 non-null  float64
 82  hardship_flag               12180 non-null  object
 83  debt_settlement_flag        12180 non-null  object
dtypes: float64(76), object(8)
memory usage: 7.8+ MB

In [13]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4702 entries, 0 to 4701
Data columns (total 84 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   loan_amnt                   4702 non-null   float64
 1   int_rate                    4702 non-null   float64
 2   installment                 4702 non-null   float64
 3   home_ownership              4702 non-null   object
 4   annual_inc                  4702 non-null   float64
 5   verification_status         4702 non-null   object
 6   loan_status                 4702 non-null   object
 7   pymnt_plan                  4702 non-null   object
 8   dti                         4702 non-null   float64
 9   delinq_2yrs                 4702 non-null   float64
 10  inq_last_6mths              4702 non-null   float64
 11  open_acc                    4702 non-null   float64
 12  pub_rec                     4702 non-null   float64
 13  revol_bal                   4702 non-null   float64
 14  total_acc                   4702 non-null   float64
 15  initial_list_status         4702 non-null   object
 16  out_prncp                   4702 non-null   float64
 17  out_prncp_inv               4702 non-null   float64
 18  total_pymnt                 4702 non-null   float64
 19  total_pymnt_inv             4702 non-null   float64
 20  total_rec_prncp             4702 non-null   float64
 21  total_rec_int               4702 non-null   float64
 22  total_rec_late_fee          4702 non-null   float64
 23  recoveries                  4702 non-null   float64
 24  collection_recovery_fee     4702 non-null   float64
 25  last_pymnt_amnt             4702 non-null   float64
 26  collections_12_mths_ex_med  4702 non-null   float64
 27  policy_code                 4702 non-null   float64
 28  application_type            4702 non-null   object
 29  acc_now_delinq              4702 non-null   float64
 30  tot_coll_amt                4702 non-null   float64
 31  tot_cur_bal                 4702 non-null   float64
 32  open_acc_6m                 4702 non-null   float64
 33  open_act_il                 4702 non-null   float64
 34  open_il_12m                 4702 non-null   float64
 35  open_il_24m                 4702 non-null   float64
 36  mths_since_rcnt_il          4702 non-null   float64
 37  total_bal_il                4702 non-null   float64
 38  il_util                     4702 non-null   float64
 39  open_rv_12m                 4702 non-null   float64
 40  open_rv_24m                 4702 non-null   float64
 41  max_bal_bc                  4702 non-null   float64
 42  all_util                    4702 non-null   float64
 43  total_rev_hi_lim            4702 non-null   float64
 44  inq_fi                      4702 non-null   float64
 45  total_cu_tl                 4702 non-null   float64
 46  inq_last_12m                4702 non-null   float64
 47  acc_open_past_24mths        4702 non-null   float64
 48  avg_cur_bal                 4702 non-null   float64
 49  bc_open_to_buy              4702 non-null   float64
 50  bc_util                     4702 non-null   float64
 51  chargeoff_within_12_mths    4702 non-null   float64
 52  delinq_amnt                 4702 non-null   float64
 53  mo_sin_old_il_acct          4702 non-null   float64
 54  mo_sin_old_rev_tl_op        4702 non-null   float64
 55  mo_sin_rcnt_rev_tl_op       4702 non-null   float64
 56  mo_sin_rcnt_tl              4702 non-null   float64
 57  mort_acc                    4702 non-null   float64
 58  mths_since_recent_bc        4702 non-null   float64
 59  mths_since_recent_inq       4702 non-null   float64
 60  num_accts_ever_120_pd       4702 non-null   float64
 61  num_actv_bc_tl              4702 non-null   float64
 62  num_actv_rev_tl             4702 non-null   float64
 63  num_bc_sats                 4702 non-null   float64
 64  num_bc_tl                   4702 non-null   float64
 65  num_il_tl                   4702 non-null   float64
 66  num_op_rev_tl               4702 non-null   float64
 67  num_rev_accts               4702 non-null   float64
 68  num_rev_tl_bal_gt_0         4702 non-null   float64
 69  num_sats                    4702 non-null   float64
 70  num_tl_120dpd_2m            4702 non-null   float64
 71  num_tl_30dpd                4702 non-null   float64
 72  num_tl_90g_dpd_24m          4702 non-null   float64
 73  num_tl_op_past_12m          4702 non-null   float64
 74  pct_tl_nvr_dlq              4702 non-null   float64
 75  percent_bc_gt_75            4702 non-null   float64
 76  pub_rec_bankruptcies        4702 non-null   float64
 77  tax_liens                   4702 non-null   float64
 78  tot_hi_cred_lim             4702 non-null   float64
 79  total_bal_ex_mort           4702 non-null   float64
 80  total_bc_limit              4702 non-null   float64
 81  total_il_high_credit_limit  4702 non-null   float64
 82  hardship_flag               4702 non-null   object
 83  debt_settlement_flag        4702 non-null   object
dtypes: float64(76), object(8)
memory usage: 3.0+ MB

In [26]:
# Per Prof. Booth, identify string columns from "train_df" besides target "loan_status"

str_cols=[]

for col in train_df.columns:
    if (train_df[col].dtype == object) & (col != "loan_status"):
        print(col)
        str_cols.append(col)
        
df_str=train_df.loc[:, str_cols]   
df_str.head()

home_ownership
verification_status
pymnt_plan
initial_list_status
application_type
hardship_flag
debt_settlement_flag

,home_ownership,verification_status,pymnt_plan,initial_list_status,application_type,hardship_flag,debt_settlement_flag
0,MORTGAGE,Not Verified,n,w,Individual,N,N
1,MORTGAGE,Source Verified,n,w,Individual,N,N
2,MORTGAGE,Source Verified,n,w,Individual,N,N
3,RENT,Not Verified,n,w,Individual,N,N
4,MORTGAGE,Source Verified,n,w,Individual,N,N

In [27]:
# Determine encoding

for col in df_str.columns:
    print(col)
    print(df_str[col].value_counts())
    print()
    print()

home_ownership
MORTGAGE    5800
RENT        4944
OWN         1371
ANY           65
Name: home_ownership, dtype: int64


verification_status
Not Verified       5301
Source Verified    4881
Verified           1998
Name: verification_status, dtype: int64


pymnt_plan
n    12180
Name: pymnt_plan, dtype: int64


initial_list_status
w    11158
f     1022
Name: initial_list_status, dtype: int64


application_type
Individual    10400
Joint App      1780
Name: application_type, dtype: int64


hardship_flag
N    11832
Y      348
Name: hardship_flag, dtype: int64


debt_settlement_flag
N    12175
Y        5
Name: debt_settlement_flag, dtype: int64

In [28]:
# Dropped columns with only one category 

df_str.drop(["pymnt_plan","debt_settlement_flag"] ,axis=1, inplace=True)

In [29]:
df_str.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12180 entries, 0 to 12179
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   home_ownership       12180 non-null  object
 1   verification_status  12180 non-null  object
 2   initial_list_status  12180 non-null  object
 3   application_type     12180 non-null  object
 4   hardship_flag        12180 non-null  object
dtypes: object(5)
memory usage: 475.9+ KB

In [30]:
# "Label Encode" columns with mulple categories

df_le = df_str.loc[: ,["initial_list_status","application_type","hardship_flag"]]
df_le["initial_list_status"] = [1 if x == "f" else 0 for x in df_le.initial_list_status]
df_le["application_type"] = [1 if x == "Joint App" else 0 for x in df_le.application_type]
df_le["hardship_flag"] = [1 if x == "Y" else 0 for x in df_le.hardship_flag]

df_le.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12180 entries, 0 to 12179
Data columns (total 3 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   initial_list_status  12180 non-null  int64
 1   application_type     12180 non-null  int64
 2   hardship_flag        12180 non-null  int64
dtypes: int64(3)
memory usage: 285.6 KB

In [31]:
df_le.head()

   initial_list_status  application_type  hardship_flag
0                    0                 0              0
1                    0                 0              0
2                    0                 0              0
3                    0                 0              0
4                    0                 0              0

In [32]:
# Create numeric columns from "train_df"

num_cols=[]

for col in train_df.columns:
    if (train_df[col].dtype != object) & (col != "loan_status"):
        print(col)
        num_cols.append(col)
        
df_num=train_df.loc[:, num_cols]   
df_num.head()

loan_amnt
int_rate
installment
annual_inc
dti
delinq_2yrs
inq_last_6mths
open_acc
pub_rec
revol_bal
total_acc
out_prncp
out_prncp_inv
total_pymnt
total_pymnt_inv
total_rec_prncp
total_rec_int
total_rec_late_fee
recoveries
collection_recovery_fee
last_pymnt_amnt
collections_12_mths_ex_med
policy_code
acc_now_delinq
tot_coll_amt
tot_cur_bal
open_acc_6m
open_act_il
open_il_12m
open_il_24m
mths_since_rcnt_il
total_bal_il
il_util
open_rv_12m
open_rv_24m
max_bal_bc
all_util
total_rev_hi_lim
inq_fi
total_cu_tl
inq_last_12m
acc_open_past_24mths
avg_cur_bal
bc_open_to_buy
bc_util
chargeoff_within_12_mths
delinq_amnt
mo_sin_old_il_acct
mo_sin_old_rev_tl_op
mo_sin_rcnt_rev_tl_op
mo_sin_rcnt_tl
mort_acc
mths_since_recent_bc
mths_since_recent_inq
num_accts_ever_120_pd
num_actv_bc_tl
num_actv_rev_tl
num_bc_sats
num_bc_tl
num_il_tl
num_op_rev_tl
num_rev_accts
num_rev_tl_bal_gt_0
num_sats
num_tl_120dpd_2m
num_tl_30dpd
num_tl_90g_dpd_24m
num_tl_op_past_12m
pct_tl_nvr_dlq
percent_bc_gt_75
pub_rec_bankruptcies
tax_liens
tot_hi_cred_lim
total_bal_ex_mort
total_bc_limit
total_il_high_credit_limit

,loan_amnt,int_rate,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,open_acc,pub_rec,revol_bal,total_acc,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_amnt,collections_12_mths_ex_med,policy_code,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_inq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit
0,13375.0,0.1797,483.34,223000.0,29.99,0.0,0.0,15.0,0.0,39728.0,38.0,12804.66,12804.66,953.33,953.33,570.34,382.99,0.0,0.0,0.0,483.34,0.0,1.0,0.0,0.0,465790.0,2.0,7.0,3.0,7.0,7.0,82290.0,70.0,1.0,1.0,24683.0,69.0,60200.0,1.0,12.0,2.0,9.0,31053.0,7317.0,77.1,0.0,0.0,160.0,350.0,3.0,3.0,1.0,3.0,8.0,0.0,1.0,4.0,2.0,5.0,18.0,7.0,17.0,4.0,15.0,0.0,0.0,0.0,5.0,100.0,50.0,0.0,0.0,577150.0,122018.0,32000.0,170200.0
1,21000.0,0.1308,478.68,123000.0,11.26,2.0,0.0,16.0,0.0,9585.0,20.0,15152.97,15152.97,10037.02,10037.02,5847.03,4189.99,0.0,0.0,0.0,478.68,0.0,1.0,0.0,0.0,60769.0,0.0,2.0,0.0,1.0,17.0,18311.0,52.0,0.0,4.0,4311.0,50.0,20900.0,1.0,0.0,1.0,5.0,3798.0,6990.0,56.0,0.0,0.0,165.0,142.0,13.0,13.0,1.0,17.0,10.0,1.0,5.0,8.0,6.0,7.0,5.0,13.0,14.0,8.0,16.0,0.0,0.0,0.0,0.0,85.0,33.3,0.0,0.0,132750.0,27896.0,15900.0,35398.0
2,20000.0,0.1240,448.95,197000.0,11.28,0.0,0.0,12.0,0.0,16708.0,36.0,15724.23,15724.23,6971.52,6971.52,4275.77,2695.75,0.0,0.0,0.0,448.95,0.0,1.0,0.0,0.0,617946.0,1.0,7.0,1.0,2.0,5.0,97335.0,108.0,0.0,0.0,11026.0,98.0,25900.0,2.0,0.0,2.0,3.0,51496.0,5892.0,73.9,0.0,0.0,254.0,239.0,30.0,5.0,3.0,173.0,5.0,1.0,3.0,3.0,3.0,5.0,26.0,4.0,7.0,3.0,12.0,0.0,0.0,0.0,1.0,85.7,33.3,0.0,0.0,628160.0,114043.0,22600.0,90340.0
3,3000.0,0.1240,100.22,45000.0,18.08,0.0,0.0,12.0,1.0,8809.0,19.0,2930.77,2930.77,81.63,81.63,69.23,12.40,0.0,0.0,0.0,85.76,1.0,1.0,0.0,568.0,20761.0,2.0,4.0,2.0,2.0,8.0,11952.0,78.0,2.0,4.0,2409.0,49.0,26600.0,4.0,4.0,2.0,6.0,1730.0,13470.0,32.3,0.0,0.0,135.0,146.0,2.0,2.0,0.0,2.0,8.0,0.0,5.0,6.0,6.0,6.0,8.0,8.0,11.0,6.0,12.0,0.0,0.0,0.0,4.0,100.0,16.7,1.0,0.0,42006.0,20761.0,19900.0,15406.0
4,30000.0,0.1612,1056.49,133000.0,27.77,0.0,2.0,13.0,0.0,65420.0,51.0,20778.03,20778.03,14763.99,14763.99,9221.97,5542.02,0.0,0.0,0.0,1056.49,0.0,1.0,0.0,0.0,237839.0,2.0,3.0,1.0,3.0,5.0,43636.0,74.0,1.0,1.0,19804.0,74.0,88100.0,2.0,11.0,3.0,4.0,18295.0,18517.0,76.7,0.0,0.0,174.0,369.0,1.0,1.0,2.0,34.0,0.0,0.0,6.0,9.0,6.0,19.0,17.0,9.0,32.0,9.0,13.0,0.0,0.0,0.0,2.0,100.0,66.7,0.0,0.0,283248.0,109056.0,79500.0,58778.0

In [34]:
# Begin scaling preprocessing

scaler = StandardScaler().fit(df_num)
df_scale = pd.DataFrame(scaler.transform(df_num), columns=df_num.columns)
df_scale.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12180 entries, 0 to 12179
Data columns (total 76 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   loan_amnt                   12180 non-null  float64
 1   int_rate                    12180 non-null  float64
 2   installment                 12180 non-null  float64
 3   annual_inc                  12180 non-null  float64
 4   dti                         12180 non-null  float64
 5   delinq_2yrs                 12180 non-null  float64
 6   inq_last_6mths              12180 non-null  float64
 7   open_acc                    12180 non-null  float64
 8   pub_rec                     12180 non-null  float64
 9   revol_bal                   12180 non-null  float64
 10  total_acc                   12180 non-null  float64
 11  out_prncp                   12180 non-null  float64
 12  out_prncp_inv               12180 non-null  float64
 13  total_pymnt                 12180 non-null  float64
 14  total_pymnt_inv             12180 non-null  float64
 15  total_rec_prncp             12180 non-null  float64
 16  total_rec_int               12180 non-null  float64
 17  total_rec_late_fee          12180 non-null  float64
 18  recoveries                  12180 non-null  float64
 19  collection_recovery_fee     12180 non-null  float64
 20  last_pymnt_amnt             12180 non-null  float64
 21  collections_12_mths_ex_med  12180 non-null  float64
 22  policy_code                 12180 non-null  float64
 23  acc_now_delinq              12180 non-null  float64
 24  tot_coll_amt                12180 non-null  float64
 25  tot_cur_bal                 12180 non-null  float64
 26  open_acc_6m                 12180 non-null  float64
 27  open_act_il                 12180 non-null  float64
 28  open_il_12m                 12180 non-null  float64
 29  open_il_24m                 12180 non-null  float64
 30  mths_since_rcnt_il          12180 non-null  float64
 31  total_bal_il                12180 non-null  float64
 32  il_util                     12180 non-null  float64
 33  open_rv_12m                 12180 non-null  float64
 34  open_rv_24m                 12180 non-null  float64
 35  max_bal_bc                  12180 non-null  float64
 36  all_util                    12180 non-null  float64
 37  total_rev_hi_lim            12180 non-null  float64
 38  inq_fi                      12180 non-null  float64
 39  total_cu_tl                 12180 non-null  float64
 40  inq_last_12m                12180 non-null  float64
 41  acc_open_past_24mths        12180 non-null  float64
 42  avg_cur_bal                 12180 non-null  float64
 43  bc_open_to_buy              12180 non-null  float64
 44  bc_util                     12180 non-null  float64
 45  chargeoff_within_12_mths    12180 non-null  float64
 46  delinq_amnt                 12180 non-null  float64
 47  mo_sin_old_il_acct          12180 non-null  float64
 48  mo_sin_old_rev_tl_op        12180 non-null  float64
 49  mo_sin_rcnt_rev_tl_op       12180 non-null  float64
 50  mo_sin_rcnt_tl              12180 non-null  float64
 51  mort_acc                    12180 non-null  float64
 52  mths_since_recent_bc        12180 non-null  float64
 53  mths_since_recent_inq       12180 non-null  float64
 54  num_accts_ever_120_pd       12180 non-null  float64
 55  num_actv_bc_tl              12180 non-null  float64
 56  num_actv_rev_tl             12180 non-null  float64
 57  num_bc_sats                 12180 non-null  float64
 58  num_bc_tl                   12180 non-null  float64
 59  num_il_tl                   12180 non-null  float64
 60  num_op_rev_tl               12180 non-null  float64
 61  num_rev_accts               12180 non-null  float64
 62  num_rev_tl_bal_gt_0         12180 non-null  float64
 63  num_sats                    12180 non-null  float64
 64  num_tl_120dpd_2m            12180 non-null  float64
 65  num_tl_30dpd                12180 non-null  float64
 66  num_tl_90g_dpd_24m          12180 non-null  float64
 67  num_tl_op_past_12m          12180 non-null  float64
 68  pct_tl_nvr_dlq              12180 non-null  float64
 69  percent_bc_gt_75            12180 non-null  float64
 70  pub_rec_bankruptcies        12180 non-null  float64
 71  tax_liens                   12180 non-null  float64
 72  tot_hi_cred_lim             12180 non-null  float64
 73  total_bal_ex_mort           12180 non-null  float64
 74  total_bc_limit              12180 non-null  float64
 75  total_il_high_credit_limit  12180 non-null  float64
dtypes: float64(76)
memory usage: 7.1 MB

In [35]:
df_scale.head()

,loan_amnt,int_rate,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,open_acc,pub_rec,revol_bal,total_acc,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_amnt,collections_12_mths_ex_med,policy_code,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_inq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit
0,-0.393112,0.736585,-0.087609,0.790279,0.309615,-0.320026,-0.695401,0.376917,-0.351986,0.979339,1.083336,-0.071368,-0.071217,-1.093789,-1.093659,-0.924224,-0.968314,-0.150981,0.0,0.0,0.053954,-0.133126,0.0,-0.009061,-0.139714,1.806319,0.785406,1.179572,2.140917,3.136183,-0.516428,0.741144,-0.020749,-0.225280,-0.669299,3.455342,0.616623,0.503602,-0.282801,3.506591,-0.132295,1.186045,1.177360,-0.430820,0.951911,-0.071082,-0.009061,0.601757,1.907460,-0.648755,-0.648350,-0.175635,-0.661807,0.131913,-0.359420,-1.167625,-0.523893,-0.989682,-0.509289,1.071847,-0.334151,0.465341,-0.525210,0.379269,0.0,-0.009061,-0.148869,1.326667,0.617581,0.500053,-0.351986,0.0,1.965731,1.010651,0.156409,2.188821
1,0.351681,-0.191716,-0.103427,0.196561,-0.473994,2.170653,-0.695401,0.539402,-0.351986,-0.354346,-0.350335,0.195949,0.196078,0.736269,0.736426,0.511144,0.847978,-0.150981,0.0,0.0,0.048334,-0.133126,0.0,-0.009061,-0.139714,-0.551749,-0.871517,-0.435953,-0.881145,-0.610564,0.220799,-0.507964,-0.832495,-0.862659,0.453420,-0.332941,-0.422608,-0.500258,-0.282801,-0.578497,-0.534629,-0.015813,-0.624212,-0.448260,0.199035,-0.071082,-0.009061,0.685436,-0.228403,-0.042949,1.009132,-0.175635,-0.194150,0.467448,0.323961,0.397217,0.610258,0.222235,-0.072617,-0.589139,0.832750,0.090251,0.608016,0.541807,0.0,-0.009061,-0.148869,-1.188713,-1.069844,0.007255,-0.351986,0.0,-0.344265,-0.585044,-0.479179,-0.399905
2,0.254003,-0.320805,-0.204342,0.635913,-0.473157,-0.320026,-0.695401,-0.110538,-0.351986,-0.039187,0.924039,0.260977,0.261102,0.118673,0.118822,0.083729,0.135087,-0.150981,0.0,0.0,0.012484,-0.133126,0.0,-0.009061,-0.139714,2.692184,-0.043055,1.179572,0.126209,0.013894,-0.663873,1.034879,1.692938,-0.862659,-1.043538,0.915749,2.202816,-0.372541,0.342678,-0.578497,-0.132295,-0.616742,2.528656,-0.506821,0.837731,-0.071082,-0.009061,2.174926,0.767648,0.986922,-0.316854,1.018135,5.016891,-0.371388,0.323961,-0.385204,-0.807431,-0.686703,-0.509289,2.093992,-0.917601,-0.784958,-0.808517,-0.108345,0.0,-0.009061,-0.148869,-0.685637,-0.991097,0.007255,-0.351986,0.0,2.230882,0.875447,-0.214679,0.655196
3,-1.406519,-0.320805,-1.388060,-0.266539,-0.188665,-0.320026,-0.695401,-0.110538,2.682121,-0.388681,-0.429984,-1.195351,-1.195107,-1.269408,-1.269280,-1.060536,-1.145120,-0.150981,0.0,0.0,-0.425476,6.485154,0.0,-0.009061,0.289225,-0.784679,0.785406,0.210257,1.133563,0.013894,-0.442705,-0.632115,0.340027,0.412098,0.453420,-0.686628,-0.477304,-0.354660,1.593635,0.783199,-0.132295,0.284652,-0.760909,-0.102659,-0.646613,-0.071082,-0.009061,0.183361,-0.187329,-0.709335,-0.814099,-0.772520,-0.695211,0.131913,-0.359420,0.397217,0.043182,0.222235,-0.290953,-0.205835,-0.139667,-0.284838,0.041403,-0.108345,0.0,-0.009061,-0.148869,0.823591,0.617581,-0.482592,2.682121,0.0,-0.815953,-0.706007,-0.321269,-0.783830
4,1.230781,0.385387,1.857873,0.255933,0.216736,-0.320026,1.759668,0.051947,-0.351986,2.116088,2.118766,0.836271,0.836348,1.688594,1.688765,1.429196,1.493022,-0.150981,0.0,0.0,0.745097,-0.133126,0.0,-0.009061,-0.139714,0.479168,0.785406,-0.112848,0.126209,0.638352,-0.663873,-0.013526,0.159639,-0.225280,-0.669299,2.548066,0.890104,1.216265,0.342678,3.166167,0.270040,-0.316277,0.334049,0.166516,0.937639,-0.071082,-0.009061,0.836058,2.102563,-0.769916,-0.979847,0.421250,0.373720,-1.210223,-0.359420,0.788427,0.893796,0.222235,2.547413,0.944078,0.054816,2.340789,0.891322,0.054193,0.0,-0.009061,-0.148869,-0.182561,0.617581,0.992851,-0.351986,0.0,0.438026,0.790900,2.031592,0.049082

In [36]:
# Concatenate all DataFrames, "df_scale", "df_le", and "df_oh"

df_train = pd.concat([df_scale, df_le, df_oh,], axis=1)

#addback in the target
df_train["loan_status"] = train_df.loan_status

#make the target numeric aswell
df_train["loan_status"] = [1 if x== "high_risk" else 0 for x in df_train.loan_status]
df_train.head()

NameError: name 'df_oh' is not defined